# Generated by Django 5.2.6 on 2025-11-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
