# Generated by Django 5.2.6 on 2025-11-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_projectmember_project_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='organizationmember',
            table='organization_members',
        ),
    ]
