version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5434:5432"
    volumes:
      - notes_postgres_data:/var/lib/postgresql/data
volumes:
  notes_postgres_data: