# Generated by Django 5.2.6 on 2025-11-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_activity_action_type_activity_timestamp_sprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_task',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
