import os

FRONTEND_BASE_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")
BACKEND_BASE_URL = os.getenv("BACKEND_URL", "http://localhost:8000")

PASSWORD_RESET_PATH = "reset-password"
EMAIL_VERIFICATION_PATH = "verify-email"

PASSWORD_RESET_URL = f"{FRONTEND_BASE_URL}/{PASSWORD_RESET_PATH}"
EMAIL_VERIFICATION_URL = f"{FRONTEND_BASE_URL}/{EMAIL_VERIFICATION_PATH}"

PASSWORD_RESET_MAIL_SENDER="tt6677798@gmail.com"